discourse/discourse-adplugin

assets/javascripts/discourse/components/google-adsense.js.es6, config/settings.yml
Hi Coaches,
Recently, we refactored the Adsense reload code because DFP ads did not load in the presence of an Adsense Ads.  See  https://github.com/team-melbourne-rgsoc2015/discourse-adplugin/commit/50ee40cdfe1f4678e896bf7888ee90a102a78f24
This worked because the original ```if(key.indexOf("google") !== -1)``` was undefining everything starting with google, even the googletag which is part of DFP.  
However, it brought 2 issues that were discovered recently.
The google cmd is part of the DFP code and the error is that it is not defined.  It runs initially on first reload, but when navigating to a post and then back, it stops pushing the ad and the command becomes undefined.  We think is is because it's conflicting with the adsense reload in: …
=> Problem with Adsense reload and DFP cmd push

assets/javascripts/discourse/components/google-dfp-ad.js.es6, assets/javascripts/discourse/templates/components/google-dfp-ad.hbs, assets/javascripts/discourse/templates/connectors/topic-above-post-stream/discourse-adplugin.hbs, assets/javascripts/discourse/templates/connectors/topic-above-suggested/discourse-adplugin.hbs, plugin.rb
Here's the fix to refresh DFP ads. It's hard to follow, but stripping out all the Ember code, the required steps are these:
On initial load:
```
googletag.pubads().enableSingleRequest();
googletag.pubads().disableInitialLoad();
googletag.enableServices();
// div for the ad slot must already be in the DOM by now
var ad = googletag.defineSlot(...);
googletag.display(divId); // the id attr of the div
googletag.pubads().refresh([ad]);
```
When it's time to fetch a new ad:
```
googletag.pubads().refresh([ad]);
```
=> FIX: refresh DFP ads after navigating between topics and lists

assets/javascripts/discourse/components/google-dfp-ad.js.es6, assets/javascripts/discourse/templates/connectors/discovery-list-container-top/discourse-adplugin.hbs, assets/javascripts/discourse/templates/connectors/post-bottom/discourse-adplugin.hbs, assets/javascripts/discourse/templates/connectors/topic-above-post-stream/discourse-adplugin.hbs, assets/javascripts/discourse/templates/connectors/topic-above-suggested/discourse-adplugin.hbs
Hi! As requested on meta (https://meta.discourse.org/t/advertising-plugin-for-discourse-serve-ads-on-your-discourse-forum-official-endorsed/33734/9?u=neil), the category of a topic list and topic will always be sent as one of the ad targeting key-values using the `discourse-category` key, and value is the slug property of the category.
Also, this PR fixes ads not refreshing when going from one topic list to another.
=> DFP: Send category slug for targeting

assets/javascripts/discourse/components/google-dfp-ad.js.es6
If topic list ad units are using targeting by discourse-category, there was no way to show them on /latest, /categories, etc. where category is not relevant. With this change, discourse-category will be set to 0 (zero) on those pages so they can be targeted too.
=> DFP: send a 0 value for discourse-category targeting on /latest, /categories, etc so that ads can show there while targeting categories

plugin.rb
I'm not 100% convinced that this fixes the issue we're seeing on iPhone on www.helloforos.com, but the extra padding on left and right was causing ad units to be wider than 320 px.
=> FIX: mobile ad with is too wide on 320px wide devices

README.md
https://github.com/discourse/discourse-adplugin.git
=> Correct Git clone URL

README.md
Readme used 2014 trust level names - updated to current names.  Also removed post number from link to Meta discussion on Trust Levels, should go to first post, not post 7.
=> Update Trust Level Names

README.md
related: https://meta.discourse.org/t/discourse-adplugin-error-occurred-with-asense-code/79501/2
=> Renamed /var/docker to /var/discourse

assets/javascripts/discourse/components/google-dfp-ad.js.es6
Ember adds a w function in the string prototype that is breaking Discourse sites from loading up the add plugin, which expects w to be null for strings in minified code.
https://emberjs.com/api/ember/3.1/classes/String/methods/w?anchor=w
=> FIX: resolve collision on ember's builtin w string function

config/settings.yml
In January, we began supporting integer-based property IDs. We still support the legacy UUID's as well.
This PR will allow for both.
=> Remove need to only allow UUID as CodeFund Property ID

assets/javascripts/discourse/components/codefund-ad.js.es6, assets/javascripts/discourse/templates/components/codefund/post-bottom.hbs, assets/javascripts/discourse/templates/components/codefund/topic-above-post-stream.hbs, assets/javascripts/discourse/templates/components/codefund/topic-above-suggested.hbs, assets/javascripts/discourse/templates/components/codefund/topic-list-top.hbs, config/settings.yml, plugin.rb
This patch resolves a bug that was introduced when we launched the new platform. It also uses the new API for CodeFund.
=> Update CodeFund Ads to use new CodeFund API

README.md, assets/javascripts/discourse/components/carbonads-ad.js.es6, assets/javascripts/discourse/templates/components/carbonads-ad.hbs, assets/javascripts/discourse/templates/connectors/discovery-list-container-top/discourse-adplugin.hbs, assets/javascripts/discourse/templates/connectors/topic-above-post-stream/discourse-adplugin.hbs, assets/stylesheets/adplugin.scss, config/locales/client.en.yml, config/locales/client.es.yml, config/locales/server.en.yml, config/locales/server.es.yml, config/settings.yml, plugin.rb
This PR adds Carbon Ads support to Discourse-AdPlugin  
```
CARBON ADS GUIDELINES
There can be only one ad per page.
The ad should be visible above-the-fold (upper 800 pixels) for desktop browser.
The ad should be visible within 3x of the mobile viewport height, starting from the top of the mobile browser.
The ad tag should be placed exactly where you'd like the ad to display.
The ad image must remain 130 × 100 pixels, unmodified and unobscured.
The ad text is up to 80 characters in length and must be clearly visible.
```
To comply with this, there are only two possible locations for the ad: above topic lists and above posts stream.
---
=> Carbon Ads Integration

README.md
It seems like my Discourse forum destroyed the image as it is not being used in any post.
I have now linked the one in meta.discourse.org
=> FIX: Wrong Image

assets/javascripts/discourse/components/ad-component.js.es6, plugin.rb
This PR depends on https://github.com/discourse/discourse/pull/7860 which changes the way `group_list` site settings are stored, storing IDs instead of group names. 
To maintain backwards compatibility, we also ship:
- A way to migrate the setting values **only** after being sure the core's code is available.
- A way to keep the feature working when we still have group names instead of IDs
=> DEV: migrate no_ads_for_groups to use IDs instead of group names

assets/javascripts/discourse/components/ad-component.js.es6, plugin.rb
Reverts discourse/discourse-adplugin#77
=> Revert "DEV: migrate no_ads_for_groups to use IDs instead of group names"

assets/javascripts/discourse/components/ad-component.js.es6, plugin.rb
This reverts commit dee02ac3ba3a080d59084fd26011b945c615ca55.
=> DEV: migrate no_ads_for_groups to use IDs instead of group names [Undo revert]

assets/javascripts/discourse/components/ad-component.js.es6
no_ads_for_groups returns a list of ids
=> FIX:  removes part of the 2.4 legacy code forgotten

assets/javascripts/discourse/components/ad-component.js.es6, test/javascripts/acceptance/adsense-test.js.es6, test/javascripts/acceptance/dfp-test.js.es6
The tests were using an incorrect value for the site setting (the name of the group instead of the id).
`no_ads_for_groups` shows groups names in the UI byt actually stores IDs.
=> FIX: re-revert db4f5f99 with updated tests

assets/javascripts/discourse/components/ad-component.js, assets/javascripts/discourse/components/ad-slot.js, assets/javascripts/discourse/helpers/slot-position.js, assets/javascripts/discourse/templates/connectors/after-topic-list-item/discourse-adplugin.js
Avoids rendering multiple empty `<tr>`s in the topic list.
We expose the ad-slot logic to determine which ads are potentially available for each slot and don't render the connector when there are none. Leaking the component logic is not ideal, but I don't see a better solution given the
current design.
=> FIX: Don't render the connector when we shouldn't display an ad in the topic list item.

app/controllers/house_ads_controller.rb, app/models/house_ad.rb, app/models/house_ad_setting.rb, assets/javascripts/discourse/controllers/admin-plugins-house-ads-show.js, assets/javascripts/discourse/routes/admin-plugins-house-ads-show.js, assets/javascripts/discourse/templates/admin/plugins-house-ads-show.hbs, assets/javascripts/initializers/initialize-ad-plugin.js, assets/stylesheets/adplugin.scss, config/locales/client.en.yml, plugin.rb, spec/models/house_ad_setting_spec.rb, spec/models/house_ad_spec.rb, spec/requests/house_ad_controller_spec.rb, spec/requests/site_controller_spec.rb, spec/system/admin_house_ad_spec.rb
This PR adds 2 new settings to house ads to control whether an ad is shown to anonymous users and logged in users.
Screenshot:
Existing ads that were created before this feature will default to true for both settings; i.e., they will remain to be visible to both anonymous and logged-in users, but it will be possible to change the settings. Turning off both settings will effectively disable the ad completely.
=> FEATURE: Add per-ad visibility settings for anons and logged-in users

assets/javascripts/discourse/templates/components/google-adsense.hbs, assets/stylesheets/adplugin.scss
We've had reports that google is complaining about cumulative layout shift when responsive ads are enabled. This adds a minimum height to responsive ad unit containers to avoid the shift that occurs when an ad loads. 
This works in my test environment, but we'll have to keep an eye on whether or not this introduces too much extra space if an ad doesn't load for whatever reason. 
📖 /t/82520
=> UX: introduce min-height for responsive ads

assets/javascripts/discourse/components/ad-slot.hbs, assets/javascripts/discourse/components/ad-slot.js, assets/javascripts/discourse/components/adbutler-ad.js, assets/javascripts/discourse/components/google-adsense.js, assets/javascripts/discourse/components/google-dfp-ad.js, assets/javascripts/discourse/components/house-ad.js, assets/javascripts/discourse/connectors/after-topic-list-item/discourse-adplugin.hbs, assets/javascripts/discourse/connectors/discovery-list-container-top/discourse-adplugin.hbs, assets/javascripts/discourse/connectors/topic-above-post-stream/discourse-adplugin.hbs, assets/javascripts/discourse/connectors/topic-above-suggested/discourse-adplugin.hbs, test/javascripts/acceptance/house-ad-test.js
In the past, the ad plugin relied on two side-effects to achieve this behaviour:
1. Components being fully destroyed/rendered when navigating between pages. This stopped working when Discourse core moved to the more efficient 'loading slider' UI
2. The `listLoading` argument. This was an implementation detail of the old discovery routing infrastructure. Core recently overhauled this and removed the `listLoading` argument, because loading is now handled properly by the Ember router.
Instead of these two properties, we can use the `currentRoute` property of Ember's router service to trigger changes when navigating between pages. A common `{{#each` trick is used to fully destroy/re-render components even if the ad network is unchanged.
=> FIX: Fully re-render ads when navigating between pages

assets/javascripts/discourse/components/google-adsense.js
This should avoid surprising error messages being printed to the console
=> DEV: Abort placing adsense if Ember component is destroyed

assets/javascripts/discourse/components/adbutler-ad.js, assets/javascripts/discourse/components/amazon-product-links.js, assets/javascripts/discourse/components/carbonads-ad.js, assets/javascripts/discourse/components/google-adsense.js, assets/javascripts/discourse/components/google-dfp-ad.js, config/locales/server.en.yml, config/settings.yml, db/migrate/20240208195100_migrate_adsense_to_exclude_groups.rb, db/migrate/20240208195101_migrate_amazon_to_exclude_groups.rb, db/migrate/20240208195102_migrate_dfp_to_exclude_groups.rb, db/migrate/20240208195103_migrate_carbon_to_exclude_groups.rb, db/migrate/20240208195104_migrate_adbutler_to_exclude_groups.rb, lib/adplugin/guardian_extensions.rb, spec/serializer/current_user_serializer_spec.rb
With the new group system for displaying ads we no longer can check if a
user belongs to a trust level group lower than specified. The other
problem is that ALL users including staff and higher trust levels all
belong to trust level 0. So without this fix if we say that an ad should
be visible to trust level 0 users then it will be shown to all users.
This fix adds a new default setting for each ad platform for excluding
trust level 3, 4, and staff users from being shown ads. It also makes the x_display_groups setting hidden as it will be removed in a later commit.
=> FIX: Add exclude groups for each ad platforms

assets/javascripts/discourse/connectors/post-bottom/discourse-adplugin.hbs, assets/javascripts/discourse/initializers/initialize-ad-plugin.js
Changes in 0948d6b19e34320f95226cc43fbce976b71ceb31 caused the post-bottom-ad component to start receiving the widget-ised 'transformedPost' instead of the original `post` model. In most cases this difference didn't matter, but it did cause noticable issues with `@model.category` and `@model.topic`.
This commit also deletes the unused `post-bottom/discourse-adplugin.hbs` connector. In the past, the adplugin itself was defining the post-bottom outlet. But now, we use RenderGlimmer to load the `post-bottom-ad` directly.
=> DEV: Pass `post` instead of `transformedPost` to post-bottom-ad

assets/javascripts/discourse/components/ad-component.js, config/settings.yml, lib/adplugin/guardian_extensions.rb, plugin.rb, test/javascripts/acceptance/adsense-test.js, test/javascripts/acceptance/dfp-test.js, test/javascripts/acceptance/house-ad-test.js, test/javascripts/acceptance/mixed-ads-test.js
If the selected group to not display ads to had its visibility set to
not be visible then this setting wouldn't work correctly because that
group wouldn't be available client side. The change moves that group
check to be server side so that we can correctly see all the groups that
should not see ads.
https://meta.discourse.org/t/294686
=> FIX: Calculate no ads for groups server side

assets/javascripts/discourse/components/google-dfp-ad.js
Switching to cross-domain iframes is recommended by google here: https://developers.google.com/publisher-tag/guides/content-security-policy
=> FEATURE: Improve DFP / Ad-manager Content-Security-Policy compat

admin/assets/javascripts/discourse/components/house-ads-category-selector.gjs, admin/assets/javascripts/discourse/components/modal/preview.gjs, admin/assets/javascripts/discourse/controllers/admin-plugins-house-ads-show.js, admin/assets/javascripts/discourse/routes/admin-plugins-house-ads-show.js, admin/assets/javascripts/discourse/templates/admin/plugins-house-ads-show.hbs, app/controllers/house_ads_controller.rb, app/models/house_ad.rb, app/models/house_ad_setting.rb, assets/javascripts/discourse/components/house-ad.js, assets/stylesheets/adplugin.scss, config/locales/client.en.yml, plugin.rb, spec/models/house_ad_setting_spec.rb, spec/models/house_ad_spec.rb, spec/requests/house_ad_controller_spec.rb, spec/requests/site_controller_spec.rb, test/javascripts/acceptance/house-ad-test.js
This PR adds the ability to apply **group** and **category** restrictions to a **house ad**.
- In order to get the group and category selectors to work within `admin/assets/javascripts/discourse/controllers/admin-plugins-house-ads-show.js` I needed to modernize the file. 
- I dropped the `bufferedProperty` implementation in favor of a vanilla ember approach
- I added `category_ids` and `group_ids` to our house ads model
- I added tests for group / category restrictions
- I added a preview button to display the house ad
- `/site.json` would return a object called `house_creatives` and a list of key value pairs that matched the ad name with the html, like so:
```js
{ AD_KEY: ad.html }
```
I need access to the category ids on the client to conditionally render the house ads so the new format …
=> FEATURE: Add group and category restriction to house ads

assets/javascripts/discourse/components/house-ad.js, test/javascripts/acceptance/house-ad-test.js
In some cases where there were category restricted house ads we were not showing ads on reload. This commit filter out all the ads that should not be shown on current page, leaving only allowed ads. So now we'll show ads on every reload in all the cases.
Internal ticket: t130920
=> FIX: show non-restricted ads instead of not showing ads at all

admin/assets/javascripts/discourse/templates/admin/plugins-house-ads-show.hbs
AceEditor is now a glimmer component (see: https://github.com/discourse/discourse/pull/28492) and it follows the "data down, actions up" pattern.
=> DEV: Update ace-editor usage

admin/assets/javascripts/discourse/components/house-ads-list-setting.hbs, admin/assets/javascripts/discourse/components/house-ads-setting.hbs, admin/assets/javascripts/discourse/templates/admin/plugins-house-ads-index.hbs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
=> DEV: Update more deprecated Font Awesome icon names

.discourse-compatibility, assets/javascripts/discourse/initializers/initialize-ad-plugin.gjs, test/javascripts/acceptance/adsense-test.js, test/javascripts/acceptance/dfp-test.js, test/javascripts/acceptance/house-ad-test.js
This PR updates the ad plugin to support the Glimmer Post Stream and refactors ad rendering logic for improved compatibility and maintainability.
Key changes:
- Introduce glimmer_post_stream_mode compatibility across all ad types and test suites.
- Replace .widget-connector with .ad-connector for ad placement after posts.
- Migrate initialize-ad-plugin.js to initialize-ad-plugin.gjs to leverage Glimmer and API improvements.
- Use withSilencedDeprecations to handle widget overrides for post ads.
- Update compatibility constraints in .discourse-compatibility.
- Refactor and expand acceptance tests for AdSense, DFP, and House Ads to run with both Glimmer and legacy post stream modes.
=> DEV: Add compatibility with the Glimmer Post Stream
